### ISSUE TITLE
incorrect default path C:\Program Files(x86)\FreeCommander XE

### ISSUE THREAD

**Issue by githubbar** [danpeig/freecommander_total7zip_installer#1]
Should be a space before (x86): "C:\Program Files (x86)\FreeCommander XE"

**Comment by danpeig** [comment]
Hi,

This field is populated automatically by Windows Environment variables. Whatever is on the system variables the tool will use.

Regards

**Comment by githubbar** [comment]
What i'm saying is you have a typo here:

- $defaultInstallPath32 = "$Env:Programfiles(x86)\FreeCommander XE"
+ $defaultInstallPath32 = "$Env:Programfiles (x86)\FreeCommander XE"

**Comment by githubbar** [comment]
What i'm saying is you have a missing space

"$Env:Programfiles(x86)\FreeCommander XE"

should be 

"$Env:Programfiles (x86)\FreeCommander XE"

**Comment by danpeig** [comment]
This is an environment variable, not a folder name. Windows Environment Variable names don't have spaces:

https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables

**Comment by githubbar** [comment]
The variable is '$Env:Programfiles' the rest is a string concatenated with it '' (x86)\FreeCommander XE'.

**Comment by danpeig** [comment]
Fixed
