### ISSUE TITLE
TotalZip shows error when entering in archive

### ISSUE THREAD

**Issue by ags1234** [danpeig/freecommander_total7zip_installer#3]
Using FreeCommander XE in Windows 11.
And freecommander_total7zip_installer-1.5.zip.

I configured the plugin manually, exactly like in Screenshot_v1.1_2.PNG.
I did not use installer script since I cannot run scripts on my system.

If I try to press Enter on a 7zip archive, I get this error.

![2022-04-23 20 27 12](https://user-images.githubusercontent.com/21011513/164917138-d666793c-bfeb-4501-ae12-893778474ee3.gif)

**Comment by AllanHigdon** [comment]
Using FreeCommander XE in Windows 8.1.
And freecommander_total7zip_installer-1.5.zip.

I had the exact same issue as the previous post.

**Comment by ags1234** [comment]
Well, looks like this software is not maintained anymore...

**Comment by danpeig** [comment]
Retested the script on clean machines and is working well with Win 10 and 11.

**Comment by ags1234** [comment]
Ok, good news.
As I wrote in the first post, the problem I have, like other users, is I cannot run scripts on the system I use Free Commander in. And since I don't have admin rights, I cannot change that.

```
total7zipinstaller.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
+ CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : UnauthorizedAccess
```

It would be great if you could provide some info on how to manually install the plugin.
Steps I did:
- uncompressed the contents of `Total7Zip.zip` in FreeCommander directory;
- used `Screenshot_v1.1_2.PNG` to configure FC to use the plugin's files.

It doesn't work, see post 1. What am I missing?

**Comment by danpeig** [comment]
You need to update _total7zip.xml_ replacing 'INSTALL_PATH' with your installation path.

**Comment by ags1234** [comment]
Oh, great! That was the problem!
It works now, thanks for the help! :)

**Comment by ags1234** [comment]
Can the variable %FcSrcPath% be used in 'INSTALL_PATH'?
It would help to make Total7zip plugin portable in a portable FC.

**Comment by danpeig** [comment]
The script already does this if you run from the app folder.

**Comment by ags1234** [comment]
I know it does, but as I said twice before, I cannot run scripts on my system.
