### ISSUE TITLE
Script feedback :)

### ISSUE THREAD

**Issue by MiroslavMikus** [danpeig/freecommander_total7zip_installer#4]
Hey I was just browsing FreeCommander Forum and just found you ps script.

Q: Did you considered using 
``` ps1
write-host hey -ForegroundColor Red
```
over your own implementation?

**Comment by danpeig** [comment]
Hi, thanks for the tip. I have custom implementation because it not only changes the color of the script output but also from the commands output. For this specific script I agree it was not necessary, just recycled to save time.
